name: CI/CD Pipeline

# Запуск на події push або pull_request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонуємо репозиторій
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Налаштовуємо Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Встановлюємо залежності
      - name: Install dependencies
        run: npm install

      # 4. Запускаємо тести
      - name: Run tests
        run: npm test

      # 5. Створюємо Docker-образ
      - name: Build Docker image
        run: docker build -t devops-practice-app .

      # 6. Логін до Docker Hub за допомогою токена
      - name: Log in to Docker Hub using access token
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 7. Завантажуємо образ у Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag devops-practice-app:latest ${{ secrets.DOCKER_USERNAME }}/devops-practice-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-practice-app:latest

      # 8. Розгортання на Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'devops-practice-app'
          heroku_email: 'kivlyukyura@gmail.com'
          docker: true

      # 9. Логін до Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 10. Завантаження образу у Amazon ECR
      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REPOSITORY: devops-practice-app
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          IMAGE_URI=941377126042.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}
          docker tag devops-practice-app:latest $IMAGE_URI:latest
          docker push $IMAGE_URI:latest

      # 11. Розгортання у Amazon ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          cluster: devops-practice-cluster
          service: devops-practice-service
          task-definition: ecs-task-definition.json
          network-configuration: awsvpcConfiguration={subnets=[subnet-031acd7a9aafdb78e,subnet-0a9f3639c2a743f84],securityGroups=[sg-0ff8003e110a804fc],assignPublicIp=ENABLED}
